server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # React Router ke saare routes ko index.html pe redirect karo
    # (Single Page Application ke liye zaroori hai)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
